### ISSUE TITLE
Avoid Jurisdiction?

### ISSUE THREAD

**Issue by sskagemo** [STIRData/data-specification#4]
Feedback from D. Koerner - jurisdiction is open for different interpretations. Maybe instead refer to the country where the registration authority is located?

**Comment by DGKoerner** [comment]
The determination of the jurisdiction for a company is highly controversial. See for example: [Tensions between European Union Law and Private International Law – impact on cross-border mobility of companies – Official Blog of UNIO](https://officialblogofunio.com/2017/04/24/tensions-between-european-union-law-and-private-international-law-impact-on-cross-border-mobility-of-companies/#_edn3) Some adhere to the business address. Others use instead the registered address to determine the seat/jurisdiction of a company. As STIRData provides both information on where a company is doing business (business address) and information on where a company is registered I do not see a spesific need to inform about the jurisdiction for the company. ISA2 core vocabulary uses jurisdiction only for persons. Therefore I suggest to drop "jurisdiction" as data element in STIRData.
